# Generated by Django 2.2.3 on 2020-02-12 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('look', models.IntegerField(default=0)),
                ('collection', models.IntegerField(default=0)),
                ('affirm', models.IntegerField(default=0)),
                ('ginfo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Blogcates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=1, null=True)),
                ('phone', models.CharField(max_length=11)),
                ('birth', models.DateTimeField(null=True)),
                ('job', models.CharField(max_length=50, null=True)),
                ('company', models.CharField(max_length=100, null=True)),
                ('school', models.CharField(max_length=100, null=True)),
                ('industry', models.CharField(max_length=100, null=True)),
                ('introduce', models.CharField(max_length=500, null=True)),
                ('status', models.IntegerField(default=0)),
                ('head_url', models.CharField(max_length=100, null=True)),
                ('notice', models.IntegerField(default=0)),
                ('fans', models.IntegerField(default=0)),
                ('vipuser', models.IntegerField(default=0)),
                ('havenoticed', models.CharField(default=0, max_length=500)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zhuanlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hide', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('blognumber', models.IntegerField(default=0)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ginfo', models.CharField(max_length=500)),
                ('affirm', models.IntegerField(default=0)),
                ('parentid', models.IntegerField(default=0)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Blog')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Users')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='bgcate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Blogcates'),
        ),
        migrations.AddField(
            model_name='blog',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Users'),
        ),
        migrations.AddField(
            model_name='blog',
            name='zlid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Zhuanlan'),
        ),
    ]
