# Generated by Django 2.2.3 on 2020-02-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='users',
            name='head_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
