# Generated by Django 2.2.3 on 2020-03-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20200307_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
