# Generated by Django 2.2.3 on 2020-03-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_blog_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_url', models.CharField(max_length=200)),
                ('pic_index', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('blog_url', models.CharField(max_length=200)),
                ('blog_title', models.CharField(max_length=100)),
                ('cid', models.IntegerField(blank=True, default=0, null=True)),
                ('addtime', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
