# Generated by Django 2.2.3 on 2020-04-25 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collect',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='users',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='users',
            name='company',
        ),
        migrations.RemoveField(
            model_name='users',
            name='havenoticed',
        ),
        migrations.RemoveField(
            model_name='users',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='users',
            name='introduce',
        ),
        migrations.RemoveField(
            model_name='users',
            name='job',
        ),
        migrations.RemoveField(
            model_name='users',
            name='school',
        ),
        migrations.RemoveField(
            model_name='users',
            name='sex',
        ),
        migrations.AddField(
            model_name='blog',
            name='today_looks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='collect',
            name='collect_blog',
            field=models.TextField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='affim_user',
            field=models.TextField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='applyid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='index.Comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='affirm_blog',
            field=models.TextField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='addtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='affirm',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='collection',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='ifcomment',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='list_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='look',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='yuanchuang',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='bghistory',
            field=models.TextField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='fans',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='notice',
            field=models.TextField(default=0),
        ),
    ]
