# Generated by Django 2.2.3 on 2020-04-10 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_url', models.CharField(max_length=200)),
                ('pic_index', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('blog_url', models.CharField(max_length=200)),
                ('blog_title', models.CharField(max_length=100)),
                ('cid', models.IntegerField(blank=True, default=0, null=True)),
                ('addtime', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=50)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
                ('addtime', models.DateTimeField(auto_now_add=True, null=True)),
                ('look', models.IntegerField(blank=True, default=0, null=True)),
                ('collection', models.IntegerField(blank=True, default=0, null=True)),
                ('affirm', models.IntegerField(blank=True, default=0, null=True)),
                ('ginfo', models.TextField()),
                ('ifcomment', models.IntegerField(blank=True, default=0, null=True)),
                ('list_order', models.IntegerField(blank=True, default=0, null=True)),
                ('beforeurl', models.CharField(blank=True, max_length=300, null=True)),
                ('yuanchuang', models.IntegerField(blank=True, default=0, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('today_looks', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blogcates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('list_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('phone', models.CharField(max_length=11)),
                ('birth', models.DateTimeField(blank=True, null=True)),
                ('job', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('school', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('introduce', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.IntegerField(default=0)),
                ('head_url', models.CharField(blank=True, max_length=500, null=True)),
                ('notice', models.IntegerField(default=0)),
                ('fans', models.IntegerField(default=0)),
                ('vipuser', models.IntegerField(default=0)),
                ('havenoticed', models.CharField(default=0, max_length=500)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('bgimg', models.CharField(blank=True, max_length=50, null=True)),
                ('bghistory', models.CharField(blank=True, max_length=500, null=True)),
                ('viptime', models.CharField(blank=True, max_length=500, null=True)),
                ('score', models.CharField(blank=True, max_length=100, null=True)),
                ('yl_1', models.CharField(blank=True, max_length=500, null=True)),
                ('yl_2', models.CharField(blank=True, max_length=500, null=True)),
                ('yl_3', models.CharField(blank=True, max_length=500, null=True)),
                ('yl_4', models.CharField(blank=True, max_length=500, null=True)),
                ('yl_5', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Zhuanlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hide', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('title', models.CharField(default='未命名', max_length=50)),
                ('list_order', models.IntegerField(default=0)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ginfo', models.CharField(max_length=500)),
                ('affirm', models.IntegerField(default=0)),
                ('parentid', models.IntegerField(default=0)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Blog')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hide', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('title', models.CharField(default='未命名', max_length=30)),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
                ('list_order', models.IntegerField(default=0)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Users')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='bgcate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Blogcates'),
        ),
        migrations.AddField(
            model_name='blog',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Users'),
        ),
        migrations.AddField(
            model_name='blog',
            name='zlid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Zhuanlan'),
        ),
    ]
