# Generated by Django 2.2.3 on 2020-04-10 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='applyid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='index.Comment'),
            preserve_default=False,
        ),
    ]
