# Generated by Django 2.2.3 on 2020-04-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_comment_applyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='affim_user',
            field=models.TextField(blank=True, default=0, null=True),
        ),
    ]
