# Generated by Django 2.2.3 on 2020-04-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_remove_users_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collect',
            name='desc',
        ),
        migrations.AddField(
            model_name='collect',
            name='collect_blog',
            field=models.TextField(blank=True, default=0, null=True),
        ),
    ]
